"""Last-letter word-game cheat — simple tkinter UI.

Run: python app.py

Workflow:
  1. Click the game window once so the cheat learns where to type into.
  2. Click back into this app, fill the prefix (and optional suffix).
  3. Click "Find & Type" (or press F8) — the app auto-switches focus to
     the game window and types the word + Enter.
  4. Hold F9 (or hold the on-screen button) to send repeating backspaces.

Roblox / DirectInput games:
  Keystrokes are sent via pydirectinput (scan-code-based SendInput), which
  DirectInput-based games like Roblox accept. The `keyboard` lib is kept
  only for global hotkey detection.

Files:
  words.csv      — generated by main.py (word, longornot, commonornot)
  blacklist.txt  — words to never pick (one per line, # comments ok)
  used_words.txt — words already played, persisted across runs
"""

from __future__ import annotations

import csv
import ctypes
import random
import threading
import time
import tkinter as tk
from collections import defaultdict
from ctypes import wintypes
from pathlib import Path
from tkinter import ttk

import keyboard
import pydirectinput

pydirectinput.PAUSE = 0           # we manage our own delays
pydirectinput.FAILSAFE = False    # don't abort when mouse goes to a corner

HERE = Path(__file__).parent
WORDS_CSV = HERE / "words.csv"
BLACKLIST = HERE / "blacklist.txt"
USED_WORDS = HERE / "used_words.txt"

# Killer mode: in last-letter chain games where the next player's word
# must start with our last N letters, ending on these combos forces them
# into a rare-start pattern (pn-, kn-, thr-, scr-, squ-, …).
HARD_SUFFIXES_2 = (
    "nk","yw", "fs", "yz", "dz", "sz", "pn", "ez", "ly", "ny", "ps", "pt", "gn", "mn", "tm", "sr", "wr", "kn", "vl",   "zy", "xy","ux",
)
HARD_SUFFIXES_3 = (
    "asm", "zal", "sph", "scr", "spl", "spr", "str", "thr", "shr", "scl", "squ",
)
HARD_SUFFIXES_4 = (
    "tapo", "sitz", "sphr", "schr", "schn", "schl", "squl", "squw",
)
    
KILLER_SUFFIXES: dict[int, tuple[str, ...]] = {
    2: HARD_SUFFIXES_2,
    3: HARD_SUFFIXES_3,
    4: HARD_SUFFIXES_4,
}


# ---------- win32 focus plumbing ------------------------------------------

user32 = ctypes.WinDLL("user32", use_last_error=True)
kernel32 = ctypes.WinDLL("kernel32", use_last_error=True)

user32.GetForegroundWindow.restype = wintypes.HWND
user32.GetWindowThreadProcessId.argtypes = [wintypes.HWND, ctypes.POINTER(wintypes.DWORD)]
user32.GetWindowThreadProcessId.restype = wintypes.DWORD
user32.AttachThreadInput.argtypes = [wintypes.DWORD, wintypes.DWORD, wintypes.BOOL]
user32.AttachThreadInput.restype = wintypes.BOOL
user32.SetForegroundWindow.argtypes = [wintypes.HWND]
user32.SetForegroundWindow.restype = wintypes.BOOL
user32.BringWindowToTop.argtypes = [wintypes.HWND]
user32.BringWindowToTop.restype = wintypes.BOOL
user32.ShowWindow.argtypes = [wintypes.HWND, ctypes.c_int]
user32.ShowWindow.restype = wintypes.BOOL
user32.IsWindow.argtypes = [wintypes.HWND]
user32.IsWindow.restype = wintypes.BOOL
user32.IsIconic.argtypes = [wintypes.HWND]
user32.IsIconic.restype = wintypes.BOOL
user32.GetWindowTextW.argtypes = [wintypes.HWND, wintypes.LPWSTR, ctypes.c_int]
user32.GetWindowTextW.restype = ctypes.c_int

SW_RESTORE = 9


def get_window_title(hwnd: int) -> str:
    buf = ctypes.create_unicode_buffer(256)
    user32.GetWindowTextW(hwnd, buf, 256)
    return buf.value


def force_foreground(hwnd: int) -> bool:
    """Reliably bring `hwnd` to the front, bypassing Windows' focus lock.

    Returns True if the call succeeded. Uses the AttachThreadInput trick
    that's been the standard workaround for SetForegroundWindow since XP.
    """
    if not hwnd or not user32.IsWindow(hwnd):
        return False
    cur_thread = kernel32.GetCurrentThreadId()
    fg = user32.GetForegroundWindow()
    fg_thread = user32.GetWindowThreadProcessId(fg, None) if fg else 0
    target_thread = user32.GetWindowThreadProcessId(hwnd, None)

    attached_fg = False
    attached_tgt = False
    try:
        if fg_thread and fg_thread != cur_thread:
            attached_fg = bool(user32.AttachThreadInput(cur_thread, fg_thread, True))
        if target_thread and target_thread != cur_thread:
            attached_tgt = bool(user32.AttachThreadInput(cur_thread, target_thread, True))

        if user32.IsIconic(hwnd):
            user32.ShowWindow(hwnd, SW_RESTORE)
        user32.BringWindowToTop(hwnd)
        ok = bool(user32.SetForegroundWindow(hwnd))
        return ok
    finally:
        if attached_fg:
            user32.AttachThreadInput(cur_thread, fg_thread, False)
        if attached_tgt:
            user32.AttachThreadInput(cur_thread, target_thread, False)


# ---------- data loading ---------------------------------------------------


def load_words() -> dict[str, list[tuple[str, bool, bool]]]:
    by_first: dict[str, list[tuple[str, bool, bool]]] = defaultdict(list)
    with WORDS_CSV.open("r", encoding="utf-8") as f:
        reader = csv.reader(f)
        next(reader)
        for row in reader:
            if len(row) != 3 or not row[0]:
                continue
            w, lo, co = row[0], row[1] == "yes", row[2] == "yes"
            by_first[w[0]].append((w, lo, co))
    return by_first


def load_set(path: Path) -> set[str]:
    if not path.exists():
        return set()
    out: set[str] = set()
    for line in path.read_text(encoding="utf-8").splitlines():
        s = line.strip().lower()
        if s and not s.startswith("#"):
            out.add(s)
    return out


def append_used(word: str) -> None:
    with USED_WORDS.open("a", encoding="utf-8") as f:
        f.write(word + "\n")


# ---------- search ---------------------------------------------------------


def score_word(
    word: str, is_long: bool, is_common: bool,
    want_long: bool, want_common: bool, killer_level: int,
) -> int:
    s = 0
    if want_common and is_common:
        s += 50
    if want_long:
        # Heavily weight actual length so the longest legal word wins,
        # regardless of whether the CSV flagged it "long".
        s += len(word) * 100
    else:
        s += min(len(word), 20)
    if killer_level:
        if word.endswith(KILLER_SUFFIXES[killer_level]):
            s += 200       # rare-start ending of the requested length
        else:
            s -= 40        # punish non-killer endings when killer is on
    s += random.randint(0, 3)
    return s


def find_word(
    by_first: dict, starts: str, ends: str,
    common: bool, long_mode: bool, killer_level: int,
    blacklist: set[str], used: set[str],
) -> str | None:
    starts = starts.lower().strip()
    ends = "" if killer_level else ends.lower().strip()
    if not starts:
        return None
    bucket = by_first.get(starts[0], [])
    best: tuple[int, str] | None = None
    for word, is_long, is_common in bucket:
        if not word.startswith(starts):
            continue
        if ends and not word.endswith(ends):
            continue
        if word in blacklist or word in used:
            continue
        sc = score_word(word, is_long, is_common, long_mode, common, killer_level)
        if best is None or sc > best[0]:
            best = (sc, word)
    return best[1] if best else None


# ---------- typing (pydirectinput — works in Roblox/DirectInput games) ----


def _press(key: str) -> None:
    pydirectinput.keyDown(key)
    pydirectinput.keyUp(key)


def _type_char(ch: str) -> None:
    # words.csv is all lowercase ascii; no shift handling needed.
    _press(ch)


def type_robotic(word: str) -> None:
    """Fast but human-ish: no typos, steady ~100 WPM with slight jitter."""
    for ch in word:
        _type_char(ch)
        time.sleep(random.uniform(0.06, 0.11))
    time.sleep(random.uniform(0.10, 0.22))
    _press("enter")


_LETTERS = "abcdefghijklmnopqrstuvwxyz"


def type_natural(word: str) -> None:
    """Human stealth typing — ~75-90 WPM with believable mistakes.

    Cadence: each char ~90-170ms (avg ~125ms ≈ 80 WPM).
    Quirks: ~5% typo+fix, ~8% short micro-pause, ~3% longer thinking pause.
    """
    i = 0
    chars = list(word)
    while i < len(chars):
        roll = random.random()

        # ~5% typo: one wrong letter, fix it
        if roll < 0.05:
            wrong = random.choice(_LETTERS)
            if wrong == chars[i]:
                wrong = random.choice(_LETTERS)
            _type_char(wrong)
            time.sleep(random.uniform(0.15, 0.35))  # notice it
            _press("backspace")
            time.sleep(random.uniform(0.08, 0.18))

        # ~3% longer "thinking" pause
        elif roll < 0.08:
            time.sleep(random.uniform(0.30, 0.70))

        # ~8% short micro-pause between letters
        elif roll < 0.16:
            time.sleep(random.uniform(0.12, 0.25))

        _type_char(chars[i])
        time.sleep(random.uniform(0.09, 0.17))
        i += 1

    time.sleep(random.uniform(0.18, 0.45))
    _press("enter")


# ---------- UI -------------------------------------------------------------


class App:
    def __init__(self, root: tk.Tk) -> None:
        self.root = root
        root.title("Last Letter Cheat")
        root.geometry("560x520")
        root.attributes("-topmost", True)
        root.resizable(True, False)
        root.minsize(460, 460)

        self.by_first = load_words()
        self.blacklist = load_set(BLACKLIST)
        self.used = load_set(USED_WORDS)
        self.last_word: str | None = None
        self.last_typed_len: int = 0      # chars we actually pressed last time
        self._backspace_running = False
        self._target_hwnd: int = 0        # set by the focus watcher

        self._build_ui()
        self.root.update_idletasks()
        self._self_hwnd = int(self.root.winfo_id())  # tk widget HWND
        # Top-level HWND is the parent of the widget HWND on Windows. We
        # use GetForegroundWindow filtering instead — simpler & robust.

        self._start_focus_watcher()
        self._register_hotkeys()

        total = sum(len(v) for v in self.by_first.values())
        self._set_status(
            f"Loaded {total:,} words  ·  blacklist {len(self.blacklist)}"
            f"  ·  used {len(self.used)}"
        )

    # -- layout
    def _build_ui(self) -> None:
        pad = {"padx": 10, "pady": 5}
        entry_font = ("Segoe UI", 14)
        frm = ttk.Frame(self.root, padding=12)
        frm.pack(fill="both", expand=True)

        ttk.Label(frm, text="Starts with:").grid(row=0, column=0, sticky="w", **pad)
        self.starts_var = tk.StringVar()
        self.starts_entry = tk.Entry(
            frm, textvariable=self.starts_var, font=entry_font,
        )
        self.starts_entry.grid(row=0, column=1, sticky="we", **pad, ipady=4)

        ttk.Label(frm, text="Ends with:").grid(row=1, column=0, sticky="w", **pad)
        self.ends_var = tk.StringVar()
        self.ends_entry = tk.Entry(
            frm, textvariable=self.ends_var, font=entry_font,
        )
        self.ends_entry.grid(row=1, column=1, sticky="we", **pad, ipady=4)

        self.common_var = tk.BooleanVar(value=True)
        self.long_var = tk.BooleanVar(value=False)
        self.killer_var = tk.BooleanVar(value=False)
        self.killer_level_var = tk.IntVar(value=3)   # 2 / 3 / 4 suffix length
        self.events_var = tk.BooleanVar(value=False)

        modes = ttk.Frame(frm)
        modes.grid(row=2, column=0, columnspan=2, sticky="we", **pad)
        ttk.Checkbutton(modes, text="Common", variable=self.common_var).pack(side="left", padx=6)
        ttk.Checkbutton(modes, text="Long",   variable=self.long_var).pack(side="left", padx=6)
        ttk.Checkbutton(
            modes, text="Killer", variable=self.killer_var, command=self._toggle_killer,
        ).pack(side="left", padx=(6, 2))
        self._killer_level_btns: list[ttk.Radiobutton] = []
        for n in (2, 3, 4):
            rb = ttk.Radiobutton(
                modes, text=str(n), variable=self.killer_level_var, value=n,
            )
            rb.pack(side="left", padx=0)
            rb.state(["disabled"])
            self._killer_level_btns.append(rb)
        ttk.Checkbutton(modes, text="Stealth", variable=self.events_var).pack(side="left", padx=(10, 6))

        self.found_var = tk.StringVar(value="—")
        found_frame = ttk.LabelFrame(frm, text="Found", padding=8)
        found_frame.grid(row=3, column=0, columnspan=2, sticky="we", **pad)
        ttk.Label(
            found_frame, textvariable=self.found_var,
            font=("Segoe UI", 16, "bold"),
        ).pack(anchor="w")

        self.target_var = tk.StringVar(value="Target: (click your game once)")
        ttk.Label(
            frm, textvariable=self.target_var, foreground="#0066aa",
            wraplength=440, justify="left",
        ).grid(row=4, column=0, columnspan=2, sticky="w", **pad)

        def cbtn(parent, text, bg, hover, command=None):
            return tk.Button(
                parent, text=text, command=command,
                bg=bg, fg="white",
                activebackground=hover, activeforeground="white",
                font=("Segoe UI", 11, "bold"),
                relief="flat", bd=0, padx=14, pady=8,
                cursor="hand2",
            )

        btns = ttk.Frame(frm)
        btns.grid(row=5, column=0, columnspan=2, sticky="we", **pad)
        cbtn(btns, "Find",              "#5b6770", "#42505a", self.on_find
             ).pack(side="left", padx=4)
        cbtn(btns, "Find & Type (F8)",  "#22a06b", "#1a8857", self.on_find_and_type
             ).pack(side="left", padx=4)
        cbtn(btns, "Use Another (F10)", "#e07a1f", "#c46612", self.on_use_another
             ).pack(side="left", padx=4)

        btns2 = ttk.Frame(frm)
        btns2.grid(row=6, column=0, columnspan=2, sticky="we", **pad)
        bksp = cbtn(btns2, "Hold Backspace (F9)", "#c1392b", "#a32a1f")
        bksp.pack(side="left", padx=4)
        bksp.bind("<ButtonPress-1>", lambda _e: self._start_backspace(switch=True))
        bksp.bind("<ButtonRelease-1>", lambda _e: self._stop_backspace())
        cbtn(btns2, "Block", "#7a2e2e", "#5a1f1f", self.on_block_word
             ).pack(side="left", padx=4)
        cbtn(btns2, "Reset used", "#6b5b95", "#564878", self.on_reset_used
             ).pack(side="left", padx=4)

        self.status = tk.StringVar(value="")
        ttk.Label(
            frm, textvariable=self.status, foreground="#555",
            wraplength=440, justify="left",
        ).grid(row=7, column=0, columnspan=2, sticky="we", **pad)

        frm.columnconfigure(1, weight=1)

    # -- focus tracking: remember the last non-self foreground window
    def _start_focus_watcher(self) -> None:
        def is_self(hwnd: int) -> bool:
            # Walk the title — robust against tk's widget-vs-toplevel HWND quirk.
            return get_window_title(hwnd) == "Last Letter Cheat"

        def tick() -> None:
            hwnd = user32.GetForegroundWindow()
            if hwnd and not is_self(hwnd):
                if hwnd != self._target_hwnd:
                    self._target_hwnd = hwnd
                    title = get_window_title(hwnd) or "(untitled)"
                    self.target_var.set(f"Target: {title[:60]}")
            self.root.after(200, tick)

        self.root.after(200, tick)

    # -- behaviour
    def _toggle_killer(self) -> None:
        on = self.killer_var.get()
        self.ends_entry.configure(state="disabled" if on else "normal")
        for rb in self._killer_level_btns:
            rb.state(["!disabled"] if on else ["disabled"])

    def _set_status(self, msg: str) -> None:
        self.status.set(msg)

    def _find(self) -> str | None:
        killer_level = self.killer_level_var.get() if self.killer_var.get() else 0
        return find_word(
            self.by_first, self.starts_var.get(), self.ends_var.get(),
            common=self.common_var.get(), long_mode=self.long_var.get(),
            killer_level=killer_level,
            blacklist=self.blacklist, used=self.used,
        )

    def on_find(self) -> None:
        t0 = time.perf_counter()
        word = self._find()
        dt = (time.perf_counter() - t0) * 1000
        if word is None:
            self.found_var.set("—")
            self.last_word = None
            self._set_status(f"No match.  ({dt:.1f} ms)")
            return
        self.found_var.set(word)
        self.last_word = word
        self._set_status(f"Picked in {dt:.1f} ms — press F8 to type.")

    def _type_word(self, word: str, prebackspaces: int = 0) -> None:
        """Send `prebackspaces` backspaces, then type the word (prefix-stripped) + Enter."""
        self.used.add(word)
        append_used(word)
        self.last_word = word

        prefix = self.starts_var.get().strip().lower()
        to_type = word[len(prefix):] if word.startswith(prefix) else word
        self.last_typed_len = len(to_type)
        self.root.after(0, self.found_var.set, word)

        natural = self.events_var.get()
        target = self._target_hwnd

        def worker() -> None:
            switched = force_foreground(target) if target else False
            if not switched:
                self.root.after(
                    0, self._set_status,
                    "Couldn't switch focus — click your game window once first.",
                )
            else:
                time.sleep(0.12)
            for _ in range(prebackspaces):
                _press("backspace")
                time.sleep(0.02)
            self.root.after(0, self._set_status, f"Typing: {to_type!r}  (word: {word})")
            if to_type:
                (type_natural if natural else type_robotic)(to_type)
            else:
                _press("enter")
            self.root.after(0, self._set_status, f"Sent: {word}")

        threading.Thread(target=worker, daemon=True).start()

    def on_find_and_type(self) -> None:
        word = self._find()
        if word is None:
            self.root.after(0, self.found_var.set, "—")
            self.root.after(0, self._set_status, "No match.")
            return
        self._type_word(word, prebackspaces=0)

    def on_use_another(self) -> None:
        """Undo the previous typed word (backspaces) and play a different one."""
        word = self._find()
        if word is None:
            self.root.after(0, self._set_status, "No other match.")
            return
        # Undo whatever we last typed. +1 in case Enter wasn't actually
        # consumed by the game and the cursor is on a new blank line — extra
        # backspace there is harmless. We don't go +1 if nothing was typed.
        n = self.last_typed_len
        self._type_word(word, prebackspaces=n)

    def on_reset_used(self) -> None:
        self.used.clear()
        if USED_WORDS.exists():
            USED_WORDS.unlink()
        self._set_status("Used-words list cleared.")

    def on_block_word(self) -> None:
        """Append the currently-displayed word to blacklist.txt and skip it forever."""
        word = self.last_word
        if not word:
            self._set_status("No word to block — find one first.")
            return
        if word in self.blacklist:
            self._set_status(f"'{word}' was already blocked.")
            return
        self.blacklist.add(word)
        with BLACKLIST.open("a", encoding="utf-8") as f:
            f.write(word + "\n")
        self._set_status(
            f"Blocked '{word}' (blacklist now {len(self.blacklist)})."
        )

    # -- backspace hold
    def _start_backspace(self, switch: bool = False) -> None:
        if self._backspace_running:
            return
        self._backspace_running = True
        target = self._target_hwnd

        def loop() -> None:
            if switch and target:
                force_foreground(target)
                time.sleep(0.08)
            while self._backspace_running:
                _press("backspace")
                time.sleep(0.06)

        threading.Thread(target=loop, daemon=True).start()

    def _stop_backspace(self) -> None:
        self._backspace_running = False

    # -- global hotkeys (work when this window is NOT focused)
    def _register_hotkeys(self) -> None:
        # F8: when pressed from inside the game, focus is already there —
        # but call force_foreground anyway in case the user pressed F8
        # from our window (e.g. right after typing the prefix).
        keyboard.add_hotkey("f8", lambda: self.on_find_and_type())
        keyboard.add_hotkey("f10", lambda: self.on_use_another())
        # F9 hold: backspace. If pressed from game, focus is there already;
        # if from our window, the switch=True branch handles it.
        keyboard.on_press_key("f9", lambda _e: self._start_backspace(switch=True))
        keyboard.on_release_key("f9", lambda _e: self._stop_backspace())


def main() -> None:
    if not WORDS_CSV.exists():
        raise SystemExit(
            f"Missing {WORDS_CSV}. Run `python main.py` first to build it."
        )
    root = tk.Tk()
    App(root)
    try:
        root.mainloop()
    finally:
        keyboard.unhook_all()


if __name__ == "__main__":
    main()
